### ISSUE TITLE
Add Requirement PySimpleGUI

### ISSUE THREAD

**Issue by s8074132** [quirin053/digikam_face_relations#2]
I had to run `pip install PySimpleGUI` in addition to `pip install -r requirements.txt`. I think, this should be added to the `requirements.txt`.

Except from this, I got it working. Thank you very much, this tool is simple, but fills the missing feature in digikam. Again, Thank you! :smile:

**Comment by quirin053** [comment]
I'm glad you like it, I'm going to work on this project some more and fix this issue in a couple of weeks.
